export const ROLES = {
  ADMIN: 'ADMIN',
  DRIVER: 'DRIVER',
  HEAD_OF_DEPARTMENT: 'HEAD_OF_DEPARTMENT',
  TRANSPORT_OFFICER: 'TRANSPORT_OFFICER',
  ADA_DAHRM: 'ADA_DAHRM',
  PROCUREMENT: 'PROCUREMENT',
} as const

export const REQUEST_STATUS = {
  PENDING_HEAD_APPROVAL: 'PENDING_HEAD_APPROVAL',
  HEAD_APPROVED: 'HEAD_APPROVED',
  HEAD_REJECTED: 'HEAD_REJECTED',
  PENDING_TRANSPORT_APPROVAL: 'PENDING_TRANSPORT_APPROVAL',
  TRANSPORT_APPROVED: 'TRANSPORT_APPROVED',
  TRANSPORT_REJECTED: 'TRANSPORT_REJECTED',
  PENDING_DA_APPROVAL: 'PENDING_DA_APPROVAL',
  ADA_APPROVED: 'ADA_APPROVED',
  ADA_REJECTED: 'ADA_REJECTED',
  PENDING_FUEL_ISSUANCE: 'PENDING_FUEL_ISSUANCE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const

export const FUEL_TYPES = {
  DIESEL: 'DIESEL',
  PETROL: 'PETROL',
} as const

export const NOTIFICATION_TYPES = {
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  REQUEST_APPROVED: 'REQUEST_APPROVED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
} as const

export const AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  DRIVER_SUBMITTED_REQUEST: 'DRIVER_SUBMITTED_REQUEST',
  HEAD_APPROVED_REQUEST: 'HEAD_APPROVED_REQUEST',
  HEAD_REJECTED_REQUEST: 'HEAD_REJECTED_REQUEST',
  TRANSPORT_APPROVED_REQUEST: 'TRANSPORT_APPROVED_REQUEST',
  TRANSPORT_REJECTED_REQUEST: 'TRANSPORT_REJECTED_REQUEST',
  ADA_APPROVED_REQUEST: 'ADA_APPROVED_REQUEST',
  ADA_REJECTED_REQUEST: 'ADA_REJECTED_REQUEST',
  FUEL_ISSUED: 'FUEL_ISSUED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
} as const